import XCTest
@testable import LoomKit

/// Interop vectors in Fixtures/vault_vectors.json were generated by the
/// desktop's backend-api/services/crypto/vault.py — these tests prove the
/// two implementations are byte-compatible before any networking exists.
final class VaultTests: XCTestCase {
    struct Vectors: Decodable {
        struct KDF: Decodable {
            let n: UInt64
            let r: UInt32
            let p: UInt32
            let kekB64: String
            enum CodingKeys: String, CodingKey {
                case n, r, p, kekB64 = "kek_b64"
            }
        }
        let password: String
        let saltB64: String
        let kdfFull: KDF
        let kdfSmall: KDF
        let dekB64: String
        let wrappedDekB64: String
        let wrapNonceB64: String
        let recordPlaintextB64: String
        let recordCiphertextB64: String
        let recordNonceB64: String

        enum CodingKeys: String, CodingKey {
            case password
            case saltB64 = "salt_b64"
            case kdfFull = "kdf_full"
            case kdfSmall = "kdf_small"
            case dekB64 = "dek_b64"
            case wrappedDekB64 = "wrapped_dek_b64"
            case wrapNonceB64 = "wrap_nonce_b64"
            case recordPlaintextB64 = "record_plaintext_b64"
            case recordCiphertextB64 = "record_ciphertext_b64"
            case recordNonceB64 = "record_nonce_b64"
        }
    }

    static let vectors: Vectors = {
        let url = Bundle.module.url(forResource: "Fixtures/vault_vectors", withExtension: "json")!
        return try! JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }()

    var v: Vectors { Self.vectors }
    func b64(_ s: String) -> Data { Data(base64Encoded: s)! }

    // MARK: - Desktop interop

    func testDeriveKEKMatchesDesktopSmallParams() throws {
        let kek = try Vault.deriveKEK(
            password: v.password, salt: b64(v.saltB64),
            params: .init(n: v.kdfSmall.n, r: v.kdfSmall.r, p: v.kdfSmall.p)
        )
        XCTAssertEqual(kek, b64(v.kdfSmall.kekB64))
    }

    func testDeriveKEKMatchesDesktopFullParams() throws {
        // Production params (n = 2^17) — ~1s by design; this is the vector
        // that proves a real vault password unlocks across platforms.
        let kek = try Vault.deriveKEK(
            password: v.password, salt: b64(v.saltB64),
            params: .init(n: v.kdfFull.n, r: v.kdfFull.r, p: v.kdfFull.p)
        )
        XCTAssertEqual(kek, b64(v.kdfFull.kekB64))
    }

    func testUnwrapDesktopWrappedDEK() throws {
        let dek = try Vault.unwrapDEK(
            wrapped: b64(v.wrappedDekB64),
            nonce: b64(v.wrapNonceB64),
            kek: b64(v.kdfFull.kekB64)
        )
        XCTAssertEqual(dek, b64(v.dekB64))
    }

    func testDecryptDesktopRecord() throws {
        let plaintext = try Vault.decryptRecord(
            ciphertext: b64(v.recordCiphertextB64),
            nonce: b64(v.recordNonceB64),
            dek: b64(v.dekB64)
        )
        XCTAssertEqual(plaintext, b64(v.recordPlaintextB64))

        let payload = try JSONSerialization.jsonObject(with: plaintext) as! [String: Any]
        XCTAssertEqual(payload["schema_version"] as? Int, 2)
        XCTAssertEqual(payload["type"] as? String, "event")
    }

    func testDesktopCanDecryptOurOutput() throws {
        // Symmetric AES-GCM: proving we decrypt our own tag-appended output
        // with the desktop's DEK + layout is the mirror-image guarantee.
        let message = Data("round trip from Swift ✓".utf8)
        let (ciphertext, nonce) = try Vault.encryptRecord(message, dek: b64(v.dekB64))
        XCTAssertEqual(ciphertext.count, message.count + Vault.gcmTagLength)
        XCTAssertEqual(nonce.count, Vault.nonceLength)
        let back = try Vault.decryptRecord(ciphertext: ciphertext, nonce: nonce, dek: b64(v.dekB64))
        XCTAssertEqual(back, message)
    }

    // MARK: - Local behavior

    func testWrapUnwrapRoundTrip() throws {
        let kek = try Vault.deriveKEK(
            password: "pw", salt: Vault.generateSalt(),
            params: .init(n: 1 << 14, r: 8, p: 1)
        )
        let dek = Vault.generateDEK()
        let (wrapped, nonce) = try Vault.wrapDEK(dek, kek: kek)
        XCTAssertEqual(wrapped.count, Vault.dekLength + Vault.gcmTagLength)
        XCTAssertEqual(try Vault.unwrapDEK(wrapped: wrapped, nonce: nonce, kek: kek), dek)
    }

    func testWrongKEKThrowsDecryptFailed() throws {
        let dek = Vault.generateDEK()
        let (wrapped, nonce) = try Vault.wrapDEK(dek, kek: b64(v.kdfFull.kekB64))
        XCTAssertThrowsError(
            try Vault.unwrapDEK(wrapped: wrapped, nonce: nonce, kek: b64(v.kdfSmall.kekB64))
        ) { error in
            XCTAssertEqual(error as? Vault.VaultError, .decryptFailed)
        }
    }

    func testTamperedCiphertextThrowsDecryptFailed() throws {
        var ciphertext = b64(v.recordCiphertextB64)
        ciphertext[5] ^= 0xFF
        XCTAssertThrowsError(
            try Vault.decryptRecord(ciphertext: ciphertext,
                                    nonce: b64(v.recordNonceB64),
                                    dek: b64(v.dekB64))
        ) { error in
            XCTAssertEqual(error as? Vault.VaultError, .decryptFailed)
        }
    }

    func testShortSaltRejected() {
        XCTAssertThrowsError(
            try Vault.deriveKEK(password: "pw", salt: Data(count: 8))
        ) { error in
            XCTAssertEqual(error as? Vault.VaultError, .saltTooShort(minimum: 16))
        }
    }

    func testFreshNoncePerEncrypt() throws {
        let dek = b64(v.dekB64)
        let (_, n1) = try Vault.encryptRecord(Data("x".utf8), dek: dek)
        let (_, n2) = try Vault.encryptRecord(Data("x".utf8), dek: dek)
        XCTAssertNotEqual(n1, n2)
    }
}
